Repository NationalBankBelgium/ngx-form-errors, pull requests merged in 2024-09, with the labels that each got.

#51 Feature/update dev deps and ci
  .editorconfig
  .github/workflows/ci.yml
  .husky/commit-msg
  .husky/pre-commit
  .prettierignore
  package-lock.json
  package.json
Labels: comp: all, ci

#52 Feature/rxjs@7
  demo-app/ng13/package-lock.json
  demo-app/ng13/package.json
  demo-app/ng14/package-lock.json
  demo-app/ng14/package.json
  package-lock.json
  package.json
Labels: enhancement, comp: all

#56 Bugfix/fix ci release publish
  release-publish.sh
Labels: bug, enhancement, ci

#57 ci(release): fix release-publish.sh script
  release-publish.sh
Labels: bug, ci

#58 ci(release): add missing npm token in ".npmrc" file in the release job
  .github/workflows/ci.yml
Labels: bug, ci
